# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dmarsden/dev/zmqpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dmarsden/dev/zmqpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmarsden/dev/zmqpp/CMakeFiles /home/dmarsden/dev/zmqpp/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dmarsden/dev/zmqpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zmqpp-example-grasslands

# Build rule for target.
zmqpp-example-grasslands: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-grasslands
.PHONY : zmqpp-example-grasslands

# fast build rule for target.
zmqpp-example-grasslands/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-grasslands.dir/build.make CMakeFiles/zmqpp-example-grasslands.dir/build
.PHONY : zmqpp-example-grasslands/fast

#=============================================================================
# Target rules for targets named zmqpp-example-simple_client

# Build rule for target.
zmqpp-example-simple_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-simple_client
.PHONY : zmqpp-example-simple_client

# fast build rule for target.
zmqpp-example-simple_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_client.dir/build.make CMakeFiles/zmqpp-example-simple_client.dir/build
.PHONY : zmqpp-example-simple_client/fast

#=============================================================================
# Target rules for targets named zmqpp-example-strawhouse

# Build rule for target.
zmqpp-example-strawhouse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-strawhouse
.PHONY : zmqpp-example-strawhouse

# fast build rule for target.
zmqpp-example-strawhouse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-strawhouse.dir/build.make CMakeFiles/zmqpp-example-strawhouse.dir/build
.PHONY : zmqpp-example-strawhouse/fast

#=============================================================================
# Target rules for targets named zmqpp-example-simple_server

# Build rule for target.
zmqpp-example-simple_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-simple_server
.PHONY : zmqpp-example-simple_server

# fast build rule for target.
zmqpp-example-simple_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_server.dir/build.make CMakeFiles/zmqpp-example-simple_server.dir/build
.PHONY : zmqpp-example-simple_server/fast

#=============================================================================
# Target rules for targets named zmqpp-static

# Build rule for target.
zmqpp-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-static
.PHONY : zmqpp-static

# fast build rule for target.
zmqpp-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/build
.PHONY : zmqpp-static/fast

#=============================================================================
# Target rules for targets named zmqpp

# Build rule for target.
zmqpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp
.PHONY : zmqpp

# fast build rule for target.
zmqpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/build
.PHONY : zmqpp/fast

#=============================================================================
# Target rules for targets named zmqpp-example-woodhouse

# Build rule for target.
zmqpp-example-woodhouse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-woodhouse
.PHONY : zmqpp-example-woodhouse

# fast build rule for target.
zmqpp-example-woodhouse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-woodhouse.dir/build.make CMakeFiles/zmqpp-example-woodhouse.dir/build
.PHONY : zmqpp-example-woodhouse/fast

#=============================================================================
# Target rules for targets named zmqpp-example-ironhouse

# Build rule for target.
zmqpp-example-ironhouse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-ironhouse
.PHONY : zmqpp-example-ironhouse

# fast build rule for target.
zmqpp-example-ironhouse/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse.dir/build.make CMakeFiles/zmqpp-example-ironhouse.dir/build
.PHONY : zmqpp-example-ironhouse/fast

#=============================================================================
# Target rules for targets named zmqpp-client

# Build rule for target.
zmqpp-client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-client
.PHONY : zmqpp-client

# fast build rule for target.
zmqpp-client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/build
.PHONY : zmqpp-client/fast

#=============================================================================
# Target rules for targets named zmqpp-example-ironhouse2

# Build rule for target.
zmqpp-example-ironhouse2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zmqpp-example-ironhouse2
.PHONY : zmqpp-example-ironhouse2

# fast build rule for target.
zmqpp-example-ironhouse2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse2.dir/build.make CMakeFiles/zmqpp-example-ironhouse2.dir/build
.PHONY : zmqpp-example-ironhouse2/fast

examples/grasslands.o: examples/grasslands.cpp.o

.PHONY : examples/grasslands.o

# target to build an object file
examples/grasslands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-grasslands.dir/build.make CMakeFiles/zmqpp-example-grasslands.dir/examples/grasslands.cpp.o
.PHONY : examples/grasslands.cpp.o

examples/grasslands.i: examples/grasslands.cpp.i

.PHONY : examples/grasslands.i

# target to preprocess a source file
examples/grasslands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-grasslands.dir/build.make CMakeFiles/zmqpp-example-grasslands.dir/examples/grasslands.cpp.i
.PHONY : examples/grasslands.cpp.i

examples/grasslands.s: examples/grasslands.cpp.s

.PHONY : examples/grasslands.s

# target to generate assembly for a file
examples/grasslands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-grasslands.dir/build.make CMakeFiles/zmqpp-example-grasslands.dir/examples/grasslands.cpp.s
.PHONY : examples/grasslands.cpp.s

examples/ironhouse.o: examples/ironhouse.cpp.o

.PHONY : examples/ironhouse.o

# target to build an object file
examples/ironhouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse.dir/build.make CMakeFiles/zmqpp-example-ironhouse.dir/examples/ironhouse.cpp.o
.PHONY : examples/ironhouse.cpp.o

examples/ironhouse.i: examples/ironhouse.cpp.i

.PHONY : examples/ironhouse.i

# target to preprocess a source file
examples/ironhouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse.dir/build.make CMakeFiles/zmqpp-example-ironhouse.dir/examples/ironhouse.cpp.i
.PHONY : examples/ironhouse.cpp.i

examples/ironhouse.s: examples/ironhouse.cpp.s

.PHONY : examples/ironhouse.s

# target to generate assembly for a file
examples/ironhouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse.dir/build.make CMakeFiles/zmqpp-example-ironhouse.dir/examples/ironhouse.cpp.s
.PHONY : examples/ironhouse.cpp.s

examples/ironhouse2.o: examples/ironhouse2.cpp.o

.PHONY : examples/ironhouse2.o

# target to build an object file
examples/ironhouse2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse2.dir/build.make CMakeFiles/zmqpp-example-ironhouse2.dir/examples/ironhouse2.cpp.o
.PHONY : examples/ironhouse2.cpp.o

examples/ironhouse2.i: examples/ironhouse2.cpp.i

.PHONY : examples/ironhouse2.i

# target to preprocess a source file
examples/ironhouse2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse2.dir/build.make CMakeFiles/zmqpp-example-ironhouse2.dir/examples/ironhouse2.cpp.i
.PHONY : examples/ironhouse2.cpp.i

examples/ironhouse2.s: examples/ironhouse2.cpp.s

.PHONY : examples/ironhouse2.s

# target to generate assembly for a file
examples/ironhouse2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-ironhouse2.dir/build.make CMakeFiles/zmqpp-example-ironhouse2.dir/examples/ironhouse2.cpp.s
.PHONY : examples/ironhouse2.cpp.s

examples/simple_client.o: examples/simple_client.cpp.o

.PHONY : examples/simple_client.o

# target to build an object file
examples/simple_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_client.dir/build.make CMakeFiles/zmqpp-example-simple_client.dir/examples/simple_client.cpp.o
.PHONY : examples/simple_client.cpp.o

examples/simple_client.i: examples/simple_client.cpp.i

.PHONY : examples/simple_client.i

# target to preprocess a source file
examples/simple_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_client.dir/build.make CMakeFiles/zmqpp-example-simple_client.dir/examples/simple_client.cpp.i
.PHONY : examples/simple_client.cpp.i

examples/simple_client.s: examples/simple_client.cpp.s

.PHONY : examples/simple_client.s

# target to generate assembly for a file
examples/simple_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_client.dir/build.make CMakeFiles/zmqpp-example-simple_client.dir/examples/simple_client.cpp.s
.PHONY : examples/simple_client.cpp.s

examples/simple_server.o: examples/simple_server.cpp.o

.PHONY : examples/simple_server.o

# target to build an object file
examples/simple_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_server.dir/build.make CMakeFiles/zmqpp-example-simple_server.dir/examples/simple_server.cpp.o
.PHONY : examples/simple_server.cpp.o

examples/simple_server.i: examples/simple_server.cpp.i

.PHONY : examples/simple_server.i

# target to preprocess a source file
examples/simple_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_server.dir/build.make CMakeFiles/zmqpp-example-simple_server.dir/examples/simple_server.cpp.i
.PHONY : examples/simple_server.cpp.i

examples/simple_server.s: examples/simple_server.cpp.s

.PHONY : examples/simple_server.s

# target to generate assembly for a file
examples/simple_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-simple_server.dir/build.make CMakeFiles/zmqpp-example-simple_server.dir/examples/simple_server.cpp.s
.PHONY : examples/simple_server.cpp.s

examples/strawhouse.o: examples/strawhouse.cpp.o

.PHONY : examples/strawhouse.o

# target to build an object file
examples/strawhouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-strawhouse.dir/build.make CMakeFiles/zmqpp-example-strawhouse.dir/examples/strawhouse.cpp.o
.PHONY : examples/strawhouse.cpp.o

examples/strawhouse.i: examples/strawhouse.cpp.i

.PHONY : examples/strawhouse.i

# target to preprocess a source file
examples/strawhouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-strawhouse.dir/build.make CMakeFiles/zmqpp-example-strawhouse.dir/examples/strawhouse.cpp.i
.PHONY : examples/strawhouse.cpp.i

examples/strawhouse.s: examples/strawhouse.cpp.s

.PHONY : examples/strawhouse.s

# target to generate assembly for a file
examples/strawhouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-strawhouse.dir/build.make CMakeFiles/zmqpp-example-strawhouse.dir/examples/strawhouse.cpp.s
.PHONY : examples/strawhouse.cpp.s

examples/woodhouse.o: examples/woodhouse.cpp.o

.PHONY : examples/woodhouse.o

# target to build an object file
examples/woodhouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-woodhouse.dir/build.make CMakeFiles/zmqpp-example-woodhouse.dir/examples/woodhouse.cpp.o
.PHONY : examples/woodhouse.cpp.o

examples/woodhouse.i: examples/woodhouse.cpp.i

.PHONY : examples/woodhouse.i

# target to preprocess a source file
examples/woodhouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-woodhouse.dir/build.make CMakeFiles/zmqpp-example-woodhouse.dir/examples/woodhouse.cpp.i
.PHONY : examples/woodhouse.cpp.i

examples/woodhouse.s: examples/woodhouse.cpp.s

.PHONY : examples/woodhouse.s

# target to generate assembly for a file
examples/woodhouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-example-woodhouse.dir/build.make CMakeFiles/zmqpp-example-woodhouse.dir/examples/woodhouse.cpp.s
.PHONY : examples/woodhouse.cpp.s

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/options.o: src/client/options.cpp.o

.PHONY : src/client/options.o

# target to build an object file
src/client/options.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/src/client/options.cpp.o
.PHONY : src/client/options.cpp.o

src/client/options.i: src/client/options.cpp.i

.PHONY : src/client/options.i

# target to preprocess a source file
src/client/options.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/src/client/options.cpp.i
.PHONY : src/client/options.cpp.i

src/client/options.s: src/client/options.cpp.s

.PHONY : src/client/options.s

# target to generate assembly for a file
src/client/options.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-client.dir/build.make CMakeFiles/zmqpp-client.dir/src/client/options.cpp.s
.PHONY : src/client/options.cpp.s

src/zmqpp/actor.o: src/zmqpp/actor.cpp.o

.PHONY : src/zmqpp/actor.o

# target to build an object file
src/zmqpp/actor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/actor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/actor.cpp.o
.PHONY : src/zmqpp/actor.cpp.o

src/zmqpp/actor.i: src/zmqpp/actor.cpp.i

.PHONY : src/zmqpp/actor.i

# target to preprocess a source file
src/zmqpp/actor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/actor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/actor.cpp.i
.PHONY : src/zmqpp/actor.cpp.i

src/zmqpp/actor.s: src/zmqpp/actor.cpp.s

.PHONY : src/zmqpp/actor.s

# target to generate assembly for a file
src/zmqpp/actor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/actor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/actor.cpp.s
.PHONY : src/zmqpp/actor.cpp.s

src/zmqpp/auth.o: src/zmqpp/auth.cpp.o

.PHONY : src/zmqpp/auth.o

# target to build an object file
src/zmqpp/auth.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/auth.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/auth.cpp.o
.PHONY : src/zmqpp/auth.cpp.o

src/zmqpp/auth.i: src/zmqpp/auth.cpp.i

.PHONY : src/zmqpp/auth.i

# target to preprocess a source file
src/zmqpp/auth.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/auth.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/auth.cpp.i
.PHONY : src/zmqpp/auth.cpp.i

src/zmqpp/auth.s: src/zmqpp/auth.cpp.s

.PHONY : src/zmqpp/auth.s

# target to generate assembly for a file
src/zmqpp/auth.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/auth.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/auth.cpp.s
.PHONY : src/zmqpp/auth.cpp.s

src/zmqpp/context.o: src/zmqpp/context.cpp.o

.PHONY : src/zmqpp/context.o

# target to build an object file
src/zmqpp/context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/context.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/context.cpp.o
.PHONY : src/zmqpp/context.cpp.o

src/zmqpp/context.i: src/zmqpp/context.cpp.i

.PHONY : src/zmqpp/context.i

# target to preprocess a source file
src/zmqpp/context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/context.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/context.cpp.i
.PHONY : src/zmqpp/context.cpp.i

src/zmqpp/context.s: src/zmqpp/context.cpp.s

.PHONY : src/zmqpp/context.s

# target to generate assembly for a file
src/zmqpp/context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/context.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/context.cpp.s
.PHONY : src/zmqpp/context.cpp.s

src/zmqpp/curve.o: src/zmqpp/curve.cpp.o

.PHONY : src/zmqpp/curve.o

# target to build an object file
src/zmqpp/curve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/curve.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/curve.cpp.o
.PHONY : src/zmqpp/curve.cpp.o

src/zmqpp/curve.i: src/zmqpp/curve.cpp.i

.PHONY : src/zmqpp/curve.i

# target to preprocess a source file
src/zmqpp/curve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/curve.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/curve.cpp.i
.PHONY : src/zmqpp/curve.cpp.i

src/zmqpp/curve.s: src/zmqpp/curve.cpp.s

.PHONY : src/zmqpp/curve.s

# target to generate assembly for a file
src/zmqpp/curve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/curve.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/curve.cpp.s
.PHONY : src/zmqpp/curve.cpp.s

src/zmqpp/frame.o: src/zmqpp/frame.cpp.o

.PHONY : src/zmqpp/frame.o

# target to build an object file
src/zmqpp/frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/frame.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/frame.cpp.o
.PHONY : src/zmqpp/frame.cpp.o

src/zmqpp/frame.i: src/zmqpp/frame.cpp.i

.PHONY : src/zmqpp/frame.i

# target to preprocess a source file
src/zmqpp/frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/frame.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/frame.cpp.i
.PHONY : src/zmqpp/frame.cpp.i

src/zmqpp/frame.s: src/zmqpp/frame.cpp.s

.PHONY : src/zmqpp/frame.s

# target to generate assembly for a file
src/zmqpp/frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/frame.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/frame.cpp.s
.PHONY : src/zmqpp/frame.cpp.s

src/zmqpp/loop.o: src/zmqpp/loop.cpp.o

.PHONY : src/zmqpp/loop.o

# target to build an object file
src/zmqpp/loop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/loop.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/loop.cpp.o
.PHONY : src/zmqpp/loop.cpp.o

src/zmqpp/loop.i: src/zmqpp/loop.cpp.i

.PHONY : src/zmqpp/loop.i

# target to preprocess a source file
src/zmqpp/loop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/loop.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/loop.cpp.i
.PHONY : src/zmqpp/loop.cpp.i

src/zmqpp/loop.s: src/zmqpp/loop.cpp.s

.PHONY : src/zmqpp/loop.s

# target to generate assembly for a file
src/zmqpp/loop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/loop.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/loop.cpp.s
.PHONY : src/zmqpp/loop.cpp.s

src/zmqpp/message.o: src/zmqpp/message.cpp.o

.PHONY : src/zmqpp/message.o

# target to build an object file
src/zmqpp/message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/message.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/message.cpp.o
.PHONY : src/zmqpp/message.cpp.o

src/zmqpp/message.i: src/zmqpp/message.cpp.i

.PHONY : src/zmqpp/message.i

# target to preprocess a source file
src/zmqpp/message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/message.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/message.cpp.i
.PHONY : src/zmqpp/message.cpp.i

src/zmqpp/message.s: src/zmqpp/message.cpp.s

.PHONY : src/zmqpp/message.s

# target to generate assembly for a file
src/zmqpp/message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/message.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/message.cpp.s
.PHONY : src/zmqpp/message.cpp.s

src/zmqpp/poller.o: src/zmqpp/poller.cpp.o

.PHONY : src/zmqpp/poller.o

# target to build an object file
src/zmqpp/poller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/poller.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/poller.cpp.o
.PHONY : src/zmqpp/poller.cpp.o

src/zmqpp/poller.i: src/zmqpp/poller.cpp.i

.PHONY : src/zmqpp/poller.i

# target to preprocess a source file
src/zmqpp/poller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/poller.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/poller.cpp.i
.PHONY : src/zmqpp/poller.cpp.i

src/zmqpp/poller.s: src/zmqpp/poller.cpp.s

.PHONY : src/zmqpp/poller.s

# target to generate assembly for a file
src/zmqpp/poller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/poller.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/poller.cpp.s
.PHONY : src/zmqpp/poller.cpp.s

src/zmqpp/proxy.o: src/zmqpp/proxy.cpp.o

.PHONY : src/zmqpp/proxy.o

# target to build an object file
src/zmqpp/proxy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/proxy.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/proxy.cpp.o
.PHONY : src/zmqpp/proxy.cpp.o

src/zmqpp/proxy.i: src/zmqpp/proxy.cpp.i

.PHONY : src/zmqpp/proxy.i

# target to preprocess a source file
src/zmqpp/proxy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/proxy.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/proxy.cpp.i
.PHONY : src/zmqpp/proxy.cpp.i

src/zmqpp/proxy.s: src/zmqpp/proxy.cpp.s

.PHONY : src/zmqpp/proxy.s

# target to generate assembly for a file
src/zmqpp/proxy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/proxy.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/proxy.cpp.s
.PHONY : src/zmqpp/proxy.cpp.s

src/zmqpp/proxy_steerable.o: src/zmqpp/proxy_steerable.cpp.o

.PHONY : src/zmqpp/proxy_steerable.o

# target to build an object file
src/zmqpp/proxy_steerable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/proxy_steerable.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/proxy_steerable.cpp.o
.PHONY : src/zmqpp/proxy_steerable.cpp.o

src/zmqpp/proxy_steerable.i: src/zmqpp/proxy_steerable.cpp.i

.PHONY : src/zmqpp/proxy_steerable.i

# target to preprocess a source file
src/zmqpp/proxy_steerable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/proxy_steerable.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/proxy_steerable.cpp.i
.PHONY : src/zmqpp/proxy_steerable.cpp.i

src/zmqpp/proxy_steerable.s: src/zmqpp/proxy_steerable.cpp.s

.PHONY : src/zmqpp/proxy_steerable.s

# target to generate assembly for a file
src/zmqpp/proxy_steerable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/proxy_steerable.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/proxy_steerable.cpp.s
.PHONY : src/zmqpp/proxy_steerable.cpp.s

src/zmqpp/reactor.o: src/zmqpp/reactor.cpp.o

.PHONY : src/zmqpp/reactor.o

# target to build an object file
src/zmqpp/reactor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/reactor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/reactor.cpp.o
.PHONY : src/zmqpp/reactor.cpp.o

src/zmqpp/reactor.i: src/zmqpp/reactor.cpp.i

.PHONY : src/zmqpp/reactor.i

# target to preprocess a source file
src/zmqpp/reactor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/reactor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/reactor.cpp.i
.PHONY : src/zmqpp/reactor.cpp.i

src/zmqpp/reactor.s: src/zmqpp/reactor.cpp.s

.PHONY : src/zmqpp/reactor.s

# target to generate assembly for a file
src/zmqpp/reactor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/reactor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/reactor.cpp.s
.PHONY : src/zmqpp/reactor.cpp.s

src/zmqpp/signal.o: src/zmqpp/signal.cpp.o

.PHONY : src/zmqpp/signal.o

# target to build an object file
src/zmqpp/signal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/signal.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/signal.cpp.o
.PHONY : src/zmqpp/signal.cpp.o

src/zmqpp/signal.i: src/zmqpp/signal.cpp.i

.PHONY : src/zmqpp/signal.i

# target to preprocess a source file
src/zmqpp/signal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/signal.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/signal.cpp.i
.PHONY : src/zmqpp/signal.cpp.i

src/zmqpp/signal.s: src/zmqpp/signal.cpp.s

.PHONY : src/zmqpp/signal.s

# target to generate assembly for a file
src/zmqpp/signal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/signal.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/signal.cpp.s
.PHONY : src/zmqpp/signal.cpp.s

src/zmqpp/socket.o: src/zmqpp/socket.cpp.o

.PHONY : src/zmqpp/socket.o

# target to build an object file
src/zmqpp/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/socket.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/socket.cpp.o
.PHONY : src/zmqpp/socket.cpp.o

src/zmqpp/socket.i: src/zmqpp/socket.cpp.i

.PHONY : src/zmqpp/socket.i

# target to preprocess a source file
src/zmqpp/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/socket.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/socket.cpp.i
.PHONY : src/zmqpp/socket.cpp.i

src/zmqpp/socket.s: src/zmqpp/socket.cpp.s

.PHONY : src/zmqpp/socket.s

# target to generate assembly for a file
src/zmqpp/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/socket.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/socket.cpp.s
.PHONY : src/zmqpp/socket.cpp.s

src/zmqpp/z85.o: src/zmqpp/z85.cpp.o

.PHONY : src/zmqpp/z85.o

# target to build an object file
src/zmqpp/z85.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/z85.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/z85.cpp.o
.PHONY : src/zmqpp/z85.cpp.o

src/zmqpp/z85.i: src/zmqpp/z85.cpp.i

.PHONY : src/zmqpp/z85.i

# target to preprocess a source file
src/zmqpp/z85.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/z85.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/z85.cpp.i
.PHONY : src/zmqpp/z85.cpp.i

src/zmqpp/z85.s: src/zmqpp/z85.cpp.s

.PHONY : src/zmqpp/z85.s

# target to generate assembly for a file
src/zmqpp/z85.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/z85.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/z85.cpp.s
.PHONY : src/zmqpp/z85.cpp.s

src/zmqpp/zap_request.o: src/zmqpp/zap_request.cpp.o

.PHONY : src/zmqpp/zap_request.o

# target to build an object file
src/zmqpp/zap_request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/zap_request.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/zap_request.cpp.o
.PHONY : src/zmqpp/zap_request.cpp.o

src/zmqpp/zap_request.i: src/zmqpp/zap_request.cpp.i

.PHONY : src/zmqpp/zap_request.i

# target to preprocess a source file
src/zmqpp/zap_request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/zap_request.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/zap_request.cpp.i
.PHONY : src/zmqpp/zap_request.cpp.i

src/zmqpp/zap_request.s: src/zmqpp/zap_request.cpp.s

.PHONY : src/zmqpp/zap_request.s

# target to generate assembly for a file
src/zmqpp/zap_request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/zap_request.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/zap_request.cpp.s
.PHONY : src/zmqpp/zap_request.cpp.s

src/zmqpp/zmqpp.o: src/zmqpp/zmqpp.cpp.o

.PHONY : src/zmqpp/zmqpp.o

# target to build an object file
src/zmqpp/zmqpp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/zmqpp.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/zmqpp.cpp.o
.PHONY : src/zmqpp/zmqpp.cpp.o

src/zmqpp/zmqpp.i: src/zmqpp/zmqpp.cpp.i

.PHONY : src/zmqpp/zmqpp.i

# target to preprocess a source file
src/zmqpp/zmqpp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/zmqpp.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/zmqpp.cpp.i
.PHONY : src/zmqpp/zmqpp.cpp.i

src/zmqpp/zmqpp.s: src/zmqpp/zmqpp.cpp.s

.PHONY : src/zmqpp/zmqpp.s

# target to generate assembly for a file
src/zmqpp/zmqpp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp-static.dir/build.make CMakeFiles/zmqpp-static.dir/src/zmqpp/zmqpp.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zmqpp.dir/build.make CMakeFiles/zmqpp.dir/src/zmqpp/zmqpp.cpp.s
.PHONY : src/zmqpp/zmqpp.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... zmqpp"
	@echo "... zmqpp-client"
	@echo "... zmqpp-example-grasslands"
	@echo "... zmqpp-example-ironhouse"
	@echo "... zmqpp-example-ironhouse2"
	@echo "... zmqpp-example-simple_client"
	@echo "... zmqpp-example-simple_server"
	@echo "... zmqpp-example-strawhouse"
	@echo "... zmqpp-example-woodhouse"
	@echo "... zmqpp-static"
	@echo "... examples/grasslands.o"
	@echo "... examples/grasslands.i"
	@echo "... examples/grasslands.s"
	@echo "... examples/ironhouse.o"
	@echo "... examples/ironhouse.i"
	@echo "... examples/ironhouse.s"
	@echo "... examples/ironhouse2.o"
	@echo "... examples/ironhouse2.i"
	@echo "... examples/ironhouse2.s"
	@echo "... examples/simple_client.o"
	@echo "... examples/simple_client.i"
	@echo "... examples/simple_client.s"
	@echo "... examples/simple_server.o"
	@echo "... examples/simple_server.i"
	@echo "... examples/simple_server.s"
	@echo "... examples/strawhouse.o"
	@echo "... examples/strawhouse.i"
	@echo "... examples/strawhouse.s"
	@echo "... examples/woodhouse.o"
	@echo "... examples/woodhouse.i"
	@echo "... examples/woodhouse.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/options.o"
	@echo "... src/client/options.i"
	@echo "... src/client/options.s"
	@echo "... src/zmqpp/actor.o"
	@echo "... src/zmqpp/actor.i"
	@echo "... src/zmqpp/actor.s"
	@echo "... src/zmqpp/auth.o"
	@echo "... src/zmqpp/auth.i"
	@echo "... src/zmqpp/auth.s"
	@echo "... src/zmqpp/context.o"
	@echo "... src/zmqpp/context.i"
	@echo "... src/zmqpp/context.s"
	@echo "... src/zmqpp/curve.o"
	@echo "... src/zmqpp/curve.i"
	@echo "... src/zmqpp/curve.s"
	@echo "... src/zmqpp/frame.o"
	@echo "... src/zmqpp/frame.i"
	@echo "... src/zmqpp/frame.s"
	@echo "... src/zmqpp/loop.o"
	@echo "... src/zmqpp/loop.i"
	@echo "... src/zmqpp/loop.s"
	@echo "... src/zmqpp/message.o"
	@echo "... src/zmqpp/message.i"
	@echo "... src/zmqpp/message.s"
	@echo "... src/zmqpp/poller.o"
	@echo "... src/zmqpp/poller.i"
	@echo "... src/zmqpp/poller.s"
	@echo "... src/zmqpp/proxy.o"
	@echo "... src/zmqpp/proxy.i"
	@echo "... src/zmqpp/proxy.s"
	@echo "... src/zmqpp/proxy_steerable.o"
	@echo "... src/zmqpp/proxy_steerable.i"
	@echo "... src/zmqpp/proxy_steerable.s"
	@echo "... src/zmqpp/reactor.o"
	@echo "... src/zmqpp/reactor.i"
	@echo "... src/zmqpp/reactor.s"
	@echo "... src/zmqpp/signal.o"
	@echo "... src/zmqpp/signal.i"
	@echo "... src/zmqpp/signal.s"
	@echo "... src/zmqpp/socket.o"
	@echo "... src/zmqpp/socket.i"
	@echo "... src/zmqpp/socket.s"
	@echo "... src/zmqpp/z85.o"
	@echo "... src/zmqpp/z85.i"
	@echo "... src/zmqpp/z85.s"
	@echo "... src/zmqpp/zap_request.o"
	@echo "... src/zmqpp/zap_request.i"
	@echo "... src/zmqpp/zap_request.s"
	@echo "... src/zmqpp/zmqpp.o"
	@echo "... src/zmqpp/zmqpp.i"
	@echo "... src/zmqpp/zmqpp.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

